#goal definition

uint8 MODE_ABS_BASE=0
uint8 MODE_REL_BASE=1
uint8 MODE_REL_TOOL=2
uint8 mode

geometry_msgs/Vector3 normal
geometry_msgs/Vector3 point_on_normal
float64 circumference_angle
float64 circumference_duration
float64 circumference_initial_velocity
float64 circumference_final_velocity
float64 circumference_initial_acceleration
float64 circumference_final_acceleration
float64 circumference_start_time

geometry_msgs/Vector3 rotation_axis
float64 rotation_angle
float64 rotation_duration
float64 rotation_initial_velocity
float64 rotation_final_velocity
float64 rotation_initial_acceleration
float64 rotation_final_acceleration
float64 rotation_start_time

float64 start_delay
float64 steady_state_thr
---
#result definition
bool success
string msg
---
#feedback
float64 time_left
geometry_msgs/Pose pose
geometry_msgs/Twist twist