#goal definition
float64[] desired_positions
float64[] durations
float64[] start_times
float64[] initial_velocities
float64[] final_velocities
float64[] initial_accelerations
float64[] final_accelerations
float64 start_delay
float64 steady_state_thr
---
#result definition
bool success
string msg
---
#feedback
float64[] positions
float64[] velocities